# .github/workflows/version-pr.yml
name: Version PR

on:
  push:
    branches:
      - main
    paths:
      - ".changeset/**"

jobs:
  get-version:
    name: Get next version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changeset.outputs.version }}
      # We add a second output to signal whether a PR should be created
      should_run: ${{ steps.changeset.outputs.should_run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get next version number
        id: changeset
        run: |
          # Get the JSON output
          CHANGESET_STATUS=$(pnpm changeset status --json)

          # Check if the 'releases' array is empty
          if [ "$(echo "$CHANGESET_STATUS" | jq '.releases | length')" -eq 0 ]; then
            echo "No changesets found. Exiting gracefully."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "Changesets found. Proceeding to create PR."
            VERSION=$(echo "$CHANGESET_STATUS" | jq -r '.releases[0].newVersion')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  create-pr:
    name: Create Version PR
    needs: get-version
    # ONLY RUN THIS JOB IF 'should_run' is true
    if: needs.get-version.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Changeset PR or update existing one
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          title: "Upcoming Release v${{ needs.get-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
